Repository astraum/sidedish, pull requests merged in 2022-04, with the labels that each got.

#23 0421 카드 디자인 및 데이터 페칭
  frontend/README.md
  frontend/public/products.json
  frontend/public/themes.json
  frontend/src/App.js
  frontend/src/components/BestProduct.js
  frontend/src/components/Button.js
  frontend/src/components/Category.js
  frontend/src/components/DiscountTag.js
  frontend/src/components/GnbMenu.js
  frontend/src/components/Header.js
  frontend/src/components/ProductCard.js
  frontend/src/convention.js
  frontend/src/fetcher.js
  frontend/src/styles/theme.js
Labels: FE

#27 Feat alan
  frontend/public/mocks/categories.json
  frontend/public/mocks/products.json
  frontend/public/mocks/themes.json
  frontend/src/App.js
  frontend/src/components/BestProduct.js
  frontend/src/components/Category.js
  frontend/src/components/DiscountTag.js
  frontend/src/components/GnbMenu.js
  frontend/src/components/Header.js
  frontend/src/components/ProductCard-temp.js
  frontend/src/fetcher.js
  frontend/src/styles/global.js
Labels: FE

#28 카테고리 목록 조회
  backend/.gitignore
  backend/src/main/java/kr/codesquad/sidedish/controller/CategoryController.java
  backend/src/main/java/kr/codesquad/sidedish/controller/dto/CategoryListResponse.java
  backend/src/main/java/kr/codesquad/sidedish/domain/Category.java
  backend/src/main/java/kr/codesquad/sidedish/domain/Subcategory.java
  backend/src/main/java/kr/codesquad/sidedish/repository/CategoryRepository.java
  backend/src/main/java/kr/codesquad/sidedish/service/CategoryService.java
  backend/src/main/resources/sql/data.sql
  backend/src/main/resources/sql/schema.sql
  backend/src/test/java/kr/codesquad/sidedish/service/CategoryServiceTest.java
Labels: BE

#38 Feat:Modal markup & event
  frontend/public/mocks/product.json
  frontend/src/App.js
  frontend/src/ModalReducer.js
  frontend/src/components/CardList.js
  frontend/src/components/Carousel.js
  frontend/src/components/DiscountTag.js
  frontend/src/components/GnbMenu.js
  frontend/src/components/Modal.js
  frontend/src/components/ProductCard.js
  frontend/src/icons/EventBadge.js
  frontend/src/icons/PlusMinus.js
  frontend/src/index.js
Labels: FE

#50 Feat:typescript 포팅
  frontend-typescript/src/ModalReducer.tsx
  frontend-typescript/src/components/CardList.tsx
  frontend-typescript/src/components/Carousel.tsx
  frontend-typescript/src/components/Category.tsx
  frontend-typescript/src/components/DiscountTag.tsx
  frontend-typescript/src/components/Gnb.tsx
  frontend-typescript/src/components/Header.tsx
  frontend-typescript/src/components/HorizontalLine.tsx
  frontend-typescript/src/components/Modal.tsx
  frontend-typescript/src/components/ProductCard.tsx
  frontend-typescript/src/components/SpecialCategory.tsx
  frontend-typescript/src/convention.ts
  frontend-typescript/src/fetcher.ts
  frontend-typescript/src/icons/EventBadge.tsx
  frontend-typescript/src/icons/LeftArrowIcon.js
  frontend-typescript/src/icons/LeftArrowIcon.tsx
  frontend-typescript/src/icons/Logo.tsx
  frontend-typescript/src/icons/PlusMinus.tsx
  frontend-typescript/src/icons/RightArrowIcon.js
  frontend-typescript/src/icons/RightArrowIcon.tsx
  frontend-typescript/src/icons/headerIcons.tsx
  frontend-typescript/src/product.ts
  frontend-typescript/src/styles/global.ts
  frontend-typescript/src/styles/styled.d.ts
  frontend-typescript/src/styles/theme.ts
  frontend-typescript/src/types.ts
  frontend/cypress/integration/pages/sidedish.spec.js
  frontend/src/App.js
  frontend/src/components/Modal.js
Labels: enhancement, FE
